#!/usr/bin/env node
// Hermes Content Poster — Prepare deslopped content for XActions posting
// Usage: node hermes-poster.js <content-file>
// Reads a content file, formats it for XActions browser scripts, outputs posting instructions

import fs from 'node:fs';
import path from 'node:path';

const CONTENT_DIR = process.env.HERMES_CONTENT_DIR || `${process.env.HOME}/.hermes/cron/output`;
const DRAFTS_DIR = path.join(CONTENT_DIR, 'drafts');

function ensureDraftsDir() {
  if (!fs.existsSync(DRAFTS_DIR)) {
    fs.mkdirSync(DRAFTS_DIR, { recursive: true });
  }
}

function parseContent(raw) {
  const lines = raw.trim().split('\n');
  const title = lines[0].replace(/[:\-–—].*$/, '').trim();
  const body = lines.slice(1).join('\n').trim();

  // Split into tweets (280 chars max, respect sentence boundaries)
  const tweets = splitIntoTweets(body);

  return { title, body, tweets };
}

function splitIntoTweets(text) {
  const maxLen = 280;
  const tweets = [];
  const sentences = text.match(/[^.!?]+[.!?]+/g) || [text];

  let current = '';
  for (const sentence of sentences) {
    if ((current + ' ' + sentence).trim().length <= maxLen) {
      current = (current + ' ' + sentence).trim();
    } else {
      if (current) tweets.push(current);
      if (sentence.length <= maxLen) {
        current = sentence.trim();
      } else {
        // Long sentence — split at word boundary
        const words = sentence.split(' ');
        current = '';
        for (const word of words) {
          if ((current + ' ' + word).length <= maxLen) {
            current = (current + ' ' + word).trim();
          } else {
            if (current) tweets.push(current);
            current = word;
          }
        }
      }
    }
  }
  if (current) tweets.push(current);

  // Add thread numbering if multiple tweets
  if (tweets.length > 1) {
    return tweets.map((t, i) => `${i + 1}/${tweets.length} ${t}`);
  }
  return tweets;
}

function generateThreadScript(tweets) {
  const threadArray = tweets.map(t => `      '${t.replace(/'/g, "\\'")}'`).join(',\n');
  return `// Generated by Hermes Content Poster
// Paste into x.com DevTools console
(() => {
  const CONFIG = {
    thread: [
${threadArray}
    ],
    delayBetweenTweets: 2000,
    dryRun: true, // SET TO false TO POST
  };
  // ... paste postThread.js below ...
})();`;
}

function main() {
  ensureDraftsDir();

  const inputFile = process.argv[2];
  if (!inputFile) {
    // List available content files
    const files = fs.readdirSync(CONTENT_DIR)
      .filter(f => f.startsWith('security-thread_') && f.endsWith('.txt'))
      .sort()
      .reverse()
      .slice(0, 10);

    if (files.length === 0) {
      console.log('No content files found. Run the security content generator first.');
      process.exit(1);
    }

    console.log('Available content files:');
    files.forEach((f, i) => console.log(`  ${i + 1}. ${f}`));
    console.log('\nUsage: node hermes-poster.js <filename>');
    process.exit(0);
  }

  const filePath = path.isAbsolute(inputFile) ? inputFile : path.join(CONTENT_DIR, inputFile);
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    process.exit(1);
  }

  const raw = fs.readFileSync(filePath, 'utf-8');
  const { title, tweets } = parseContent(raw);

  console.log(`\n${'='.repeat(60)}`);
  console.log(`Title: ${title}`);
  console.log(`Tweets: ${tweets.length}`);
  console.log(`${'='.repeat(60)}\n`);

  tweets.forEach((t, i) => {
    console.log(`[Tweet ${i + 1}] (${t.length} chars)`);
    console.log(t);
    console.log();
  });

  // Save draft
  const draftPath = path.join(DRAFTS_DIR, `draft-${Date.now()}.txt`);
  fs.writeFileSync(draftPath, `${title}\n\n${tweets.join('\n\n---\n\n')}`);
  console.log(`Draft saved: ${draftPath}`);

  // Output thread script
  const script = generateThreadScript(tweets);
  const scriptPath = draftPath.replace('.txt', '-thread.js');
  fs.writeFileSync(scriptPath, script);
  console.log(`Thread script: ${scriptPath}`);
  console.log('\nTo post: open x.com, open DevTools, paste the thread script, set dryRun: false, run.');
}

main();
